# Generated by Django 6.1.1 on 2026-09-17 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=100)),
                ('salary', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20)),
                ('experience', models.CharField(choices=[('fresher', 'Fresher'), ('1-2', '1-2 Years'), ('3-5', '3-5 Years'), ('5+', '5+ Years')], max_length=20)),
                ('skills', models.CharField(help_text='Enter skills separated by commas', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
